### ISSUE TITLE
Rank for use of certain vehicles

### ISSUE THREAD

**Issue by AngusDLX** [Wyqer/KP_Ranks#6]
## Feature request

Congratulations on the idea! Managing players  persistently in the missions and giving them a reason for career advancement is one of those missing in Arma 3. I had the idea of designing a mod like this a long time ago but it did not because my programming level is still very low.

Have you considered the possibility of authorizing the use of vehicles such as airplanes / helicopters or even tanks / apcs? (especially when it involves missions where they cost something)

**How it would work**

- The player must have an "x" score in order to reach the pilot trainning

- But for him to have access to piloting and be pilot, he must be authorized by KP Admin or someone with the status of "instructor".

**Solutions in question of score in vehicles (for a player does not reach levels so fast just by playing with vehicles and dropping infantry sessions)**

- Reduce the score gain in vehicles to reach levels when the player is pilot or tank / apc driver gunner etc when only they are in those vehicles.

**Comment by Wyqer** [comment]
I'll implement a small API, which mission/content creators can use to easily get some data from KP Ranks, e.g. score/ranks of the players.
Some basic functions like:
* Has player X a rank of at least Y (would return true or false)
* Get rank of player X
* Set rank of player X to Y
* Get score of player X
* Set score of player X to Y
* Add score X to player Y (positive or negative values, of course)

Maybe something else I didn't think of, but currently I think these would be all the needed functions for e.g. a mission creator to do something like "If player has at least rank X, he can fly helicopters" or "When players complete this task, add X score to all of them", etc.
So it could be implemented as compatibility in e.g. Liberation.

**Comment by AngusDLX** [comment]
Good to know, this seems to be the right way, thank you Wyqer!

**Comment by Wyqer** [comment]
Commited above functions:
https://github.com/KillahPotatoes/KP-Ranks/commit/eb9ab1c20c4be4d3b549098b7a22a86fca8e07c0
https://github.com/KillahPotatoes/KP-Ranks/commit/afe3f9f51ff22e455f1f3eb1dfa41bf9f89dec69
